# Generated by Django 3.1.1 on 2020-09-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('StudentNumber', models.CharField(max_length=10)),
                ('UserEmail', models.EmailField(max_length=254)),
                ('UserName', models.CharField(max_length=16, null=True, unique=True)),
                ('UserBbsn', models.CharField(max_length=16, null=True)),
                ('UserPassword', models.CharField(max_length=16)),
                ('SignTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('Collect', models.IntegerField(null=True)),
                ('Praise', models.IntegerField(null=True)),
                ('Content', models.TextField(null=True)),
                ('Comment', models.TextField(null=True)),
                ('IssueTime', models.DateTimeField(auto_now=True, max_length=19, null=True)),
                ('UserName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_info', to_field='UserName')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article_Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=64, null=True)),
                ('IssuePlate', models.CharField(max_length=8, null=True)),
                ('IssueClassify', models.CharField(max_length=8, null=True)),
                ('Title', models.CharField(max_length=50, null=True)),
                ('UserName', models.CharField(max_length=16, null=True)),
                ('IssueTime', models.DateTimeField(auto_now=True, max_length=19, null=True)),
                ('Popularity', models.IntegerField(default=0)),
                ('Id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_article')),
            ],
            options={
                'ordering': ['-IssueTime'],
            },
        ),
    ]
