# Generated by Django 3.1.1 on 2020-09-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_interaction',
            old_name='Id',
            new_name='Nid',
        ),
    ]
