"""
Django settings for configure project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_NAME = 'app'    # 定义项目名（views.py文件所处的目录的名称）
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vw+9vxgoxvt=vv=&wf06re5q%7txmq-@ae#roz69r(3l!5422j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', ]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sslserver',
    'werkzeug_debugger_runserver',
    'django_extensions',
    'djangosecure',
    APP_NAME,

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',      # 防止跨站请求伪造
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# MIDDLEWARE_CLASSES = [
#     'djangosecure.middleware.security.SecurityMiddleware',
# ]

# 设置缓存为Redis
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache', # 设置缓存到redis中
#         'LOCATION': 'REDIS://127.0.0.1:6379',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',    # 设置使用django-redis来操作redis
#             'CONNECTION_POOL_KWARGS': { 'max_connections': 100 },   # 设置连接池池数目
#             #'PASSWORD': '1312354634'   # 设置访问密码
#         }
#     }
# }


#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO','https')
SECURE_SSL_REDIRECT = False  # 强制将http转化为https


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  #采用数据库的方式存储session
SESSION_COOKIE_NAME = 'sessionid'   #sessiond的cookie保存在浏览器上时的key，为‘sessionid’时则会为随机字符串
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_HTTPONLY = False

CONN_MAX_AGE = True  #持久化数据库连接

ROOT_URLCONF = 'configure.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, APP_NAME + '/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 注册自定义过滤器
            "libraries": {
                'my_tags': APP_NAME + '.filter.mytags'
            }
        },
    },
]

WSGI_APPLICATION = 'configure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us' #设置为中文

TIME_ZONE = 'Asia/Shanghai'         #设置时间为上海时间

USE_I18N = True

USE_L10N = True

USE_TZ = False   #为false时，表示纠正时区


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/' #设置静态文件存储相对路径

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, APP_NAME + STATIC_URL), #设置静态文件存储根路径
)
